enum SiteCategory {
  humanities('인문대학'),
  social('사회과학대학'),
  nature('자연과학대학'),
  gyeongsang('경상대학'),
  engineer('공과대학'),
  it('IT대학'),
  agriculture('농업생명과학대학'),
  art('예술대학'),
  education('사범대학'),
  medical('의과대학'),
  dental('치과대학'),
  veterinary('수의과대학'),
  lifeScience('생활과학대학'),
  nurse('간호대학'),
  pharmacy('약학대학'),
  ecology('생태환경대학'),
  scienceTech('과학기술대학'),
  publicAdmin('행정학부'),
  autonomous('자율전공'),
  faulty('융합학부'),
  knu('경북대'),
  sw('소프트웨어교육원');

  final String koreaName;

  const SiteCategory(this.koreaName);
}

enum SiteEnum {
  korean('국어국문학과', 'korean', SiteCategory.humanities),
  english('영어영문학과', 'english', SiteCategory.humanities),
  history('사학과', 'history', SiteCategory.humanities),
  philosophy('철학과', 'philosophy', SiteCategory.humanities),
  french('불어불문학과', 'french', SiteCategory.humanities),
  german('독어독문학과', 'german', SiteCategory.humanities),
  aran('고고인류학과', 'aran', SiteCategory.humanities),
  hanmun('한문학과', 'hanmun', SiteCategory.humanities),
  //중어중문학과,일어일문학과,노어노문학과
  politics('정치외교학과', 'politics', SiteCategory.social),
  socio('사회학과', 'socio', SiteCategory.social),
  geog('지리학과', 'geog', SiteCategory.social),
  lis('문헌정보학과', 'lis', SiteCategory.social),
  psychology('심리학과', 'psychology', SiteCategory.social),
  knusw('사회복지학부', 'knusw', SiteCategory.social),
  masscom('미디어커뮤니케이션학과', 'masscom', SiteCategory.social),
  math('수학과', 'math', SiteCategory.nature),
  physics('물리학과', 'physics', SiteCategory.nature),
  chem('화학과', 'chem', SiteCategory.nature),
  stat('통계학과', 'stat', SiteCategory.nature),
  //생명과학부
  //지구시스템과학부
  econ('경제통상학부', 'econ', SiteCategory.gyeongsang),
  kbiz('경영학부', 'kbiz', SiteCategory.gyeongsang),
  material('신소재공학부', 'material', SiteCategory.engineer),
  me('기계공학부', 'me', SiteCategory.engineer),
  arch('건축학부', 'arch', SiteCategory.engineer),
  civil('토목공학과', 'civil', SiteCategory.engineer),
  appchem('응용화학과', 'appchem', SiteCategory.engineer),
  cheme('화학공학과', 'cheme', SiteCategory.engineer),
  knupolymer('고분자공학과', 'knupolymer', SiteCategory.engineer),
  textileng('섬유시스템공학과', 'textileng', SiteCategory.engineer),
  env('환경공학과', 'env', SiteCategory.engineer),
  soee('에너지공학부', 'soee', SiteCategory.engineer),
  //전자공학부
  smobile('모바일공학전공', 'smobile', SiteCategory.it),
  electric('전기공학과', 'electric', SiteCategory.it),
  seeai('인공지능전공', 'seeai', SiteCategory.it),
  cse('컴퓨터학부', 'cse', SiteCategory.it),
  kac('환경생명화학전공', 'kac', SiteCategory.agriculture),
  pbs('식물생명화학전공', 'pbs', SiteCategory.agriculture),
  plantmed('식물의학과', 'plantmed', SiteCategory.agriculture),
  foodbio('식품공학부', 'foodbio', SiteCategory.agriculture),
  treei('임산공학전공', 'treei', SiteCategory.agriculture),
  horti('원예과학과', 'horti', SiteCategory.agriculture),
  biofiber('바이오섬유소재학과', 'biofiber', SiteCategory.agriculture),
  acen('농업토목공학전공', 'acen', SiteCategory.agriculture),
  bime('생물산업기계공학전공', 'bime', SiteCategory.agriculture),
  knuagec('식품자원경제학과', 'knuagec', SiteCategory.agriculture),
  aifm('농산업학과', 'aifm', SiteCategory.agriculture),
  //사범대학
  //의과대학
  //치과대학
  veterinary('수의과대학', 'veterinary', SiteCategory.veterinary),
  knuchild('아동학부', 'knuchild', SiteCategory.lifeScience),
  fashion('의류학과', 'fashion', SiteCategory.lifeScience),
  fsnu('식품영양학과', 'fsnu', SiteCategory.lifeScience),
  nurse('간호학과', 'nurse', SiteCategory.nurse),
  knupharmacy('약학과', 'knupharmacy', SiteCategory.pharmacy),
  //생태환경대학
  //과학기술대학
  puad('행정학부', 'puad', SiteCategory.publicAdmin),
  udm('자율전공부', 'udm', SiteCategory.autonomous),
  //융합학부
  knu('경북대', 'knu', SiteCategory.knu),
  sw('소프트웨어교육원', 'sw', SiteCategory.sw);

  final String koreaName;
  final String englishName;
  final SiteCategory category;

  const SiteEnum(this.koreaName, this.englishName, this.category);

  static Map<String, SiteEnum> get getType => {
        '국어국문학과': korean,
        '영어영문학과': english,
        '사학과': history,
        '철학과': philosophy,
        '불어불문학과': french,
        '독어독문학과': german,
        '고고인류학과': aran,
        '한문학과': hanmun,
        '정치외교학과': politics,
        '사회학과': socio,
        '지리학과': geog,
        '문헌정보학과': lis,
        '심리학과': psychology,
        '사회복지학부': knusw,
        '미디어커뮤니케이션학과': masscom,
        '수학과': math,
        '물리학과': physics,
        '화학과': chem,
        '통계학과': stat,
        '경제통상학부': econ,
        '경영학부': kbiz,
        '신소재공학부': material,
        '기계공학부': me,
        '건축학부': arch,
        '토목공학과': civil,
        '응용화학과': appchem,
        '화학공학과': cheme,
        '고분자공학과': knupolymer,
        '섬유시스템공학과': textileng,
        '환경공학과': env,
        '에너지공학부': soee,
        '모바일공학전공': smobile,
        '전기공학과': electric,
        '인공지능전공': seeai,
        '컴퓨터학부': cse,
        '환경생명화학전공': kac,
        '식물생명화학전공': pbs,
        '식물의학과': plantmed,
        '식품공학부': foodbio,
        '임산공학전공': treei,
        '원예과학과': horti,
        '바이오섬유소재학과': biofiber,
        '농업토목공학전공': acen,
        '생물산업기계공학전공': bime,
        '식품자원경제학과': knuagec,
        '농산업학과': aifm,
        '수의과대학': veterinary,
        '아동학부': knuchild,
        '의류학과': fashion,
        '식품영양학과': fsnu,
        '간호학과': nurse,
        '약학과': knupharmacy,
        '행정학부': puad,
        '자율전공부': udm,
        '경북대': knu,
        '소프트웨어교육원': sw,
      };
}
